modality: wifi-csi

protocol: protocol1

data_unit: frame

random_split:
  ratio: 0.8
  random_seed: 0
  train_dataset:
    split: training
    scenes: None
    subjects: None
    actions: all
  val_dataset:
    split: validation
    scenes: None
    subjects: None
    actions: all

cross_scene_split:
  train_dataset:
    split: training
    scenes: [ E01, E02, E03 ]   # [ E01, E02, E03 ]
    subjects: [S01, S02, S03, S04, S05, S06, S07, S08, S09, S10, S11, S12, S13, S14, S15, S16, S17, S18, S19, S20, S21, S22, S23, S24, S25, S26, S27, S28, S29, S30]  # None
    actions: all
  val_dataset:
    split: validation
    scenes: [ E04 ]
    subjects: [S31, S32, S33, S34, S35, S36, S37, S38, S39, S40]  # None
    actions: all

cross_subject_split:
  train_dataset:
    split: training
    scenes: None
    subjects: [ S01, S02, S03, S04, S06, S07, S08, S09, S11, S12, S13, S14, S16, S17, S18, S19, S21, S22, S23, S24, S26, S27, S28, S29, S31, S32, S33, S34, S36, S37, S38, S39 ]
    # subjects: [S01]  # None
    actions: all
  val_dataset:
    split: validation
    scenes: None
    subjects: [ S05, S10, S15, S20, S25, S30, S35, S40 ]
    # subjects: [ S05]
    actions: all

manual_split:
  train_dataset:
    split: training
    scenes: None
    subjects: [S01, S02, S03, S04, S05, S06, S07, S08, S09, S10, S11, S12, S13, S14, S15, S16, S17, S18, S19, S20, S21, S22, S23, S24, S25, S26, S27, S28, S29, S30, S31, S32, S33, S34, S35, S36, S37, S38, S39, S40]
    actions: [A01, A02, A03, A04, A05, A06, A07, A08, A09, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21]
  val_dataset:
    split: validation
    scenes: None
    subjects: [S01, S02, S03, S04, S05, S06, S07, S08, S09, S10, S11, S12, S13, S14, S15, S16, S17, S18, S19, S20, S21, S22, S23, S24, S25, S26, S27, S28, S29, S30, S31, S32, S33, S34, S35, S36, S37, S38, S39, S40]
    actions: [A22, A23, A24, A25, A26, A27]


zero_shot_split:
  train_dataset:
    split: training
    scenes: None
    subjects: [ S01, S02, S03, S04, S06, S07, S08, S09, S11, S12, S13, S14, S16, S17, S18, S19, S21, S22, S23, S24, S26, S27, S28, S29, S31, S32, S33, S34, S36, S37, S38, S39 ]
    # subjects: [S01]  # None
    actions: [A01, A06, A07, A08, A09, A10, A11, A12, A15, A16, A24, A25, A26]
  val_dataset:
    split: validation
    scenes: None
    subjects: [ S05, S10, S15, S20, S25, S30, S35, S40 ]
    # subjects: [ S05]
    actions: [A02, A03, A04, A05, A13, A14, A17, A18, A19, A20, A21, A22, A23, A27]

split_to_use: random_split

init_rand_seed: 0   # 0
train_loader:
  batch_size: 32   # 1024
validation_loader:
  batch_size: 32  # 1024
output_folder: ./ckpt/


seed: 42
dataset_root: /root/autodl-tmp/WIFI_Pose_Estimation/MMFi_Dataset/dataset
batch_size: 32   # 32
max_device_batch_size: 256
base_learning_rate: 0.001
total_epoch: 50
dataset_name: mmfi-csi
num_person: 1
setting: protocol1-s1
experiment_name: DT-Pose-ratio80   # as_our_p1s1_transformer
training_semi: False
pretrained_model_path: pretrain_weights/mmfi-csi/protocol1-s1/pretrain_our_ratio80.pt
save_path: pose_weights
